### ISSUE TITLE
Beise varmepumpehus

### ISSUE THREAD

**Issue by GardF** [GardF/FamilienAS#22]

**Comment by GardF** [comment]
Vi kan spørre Aina om å låne koster + maling. VI burde kjøpe blomster eller vin til henne da det var litt jobb det greiene her.

**Comment by GardF** [comment]
> Vi kan spørre Aina om å låne koster + maling. VI burde kjøpe blomster eller vin til henne da det var litt jobb det greiene her.

Jeg kan spørre henne senere i dag.

**Comment by 12m34** [comment]
Skal vi sette som må å gjøre dette lørdag morgen? @GardF
