### ISSUE TITLE
Vaske terrasse rekkverk

### ISSUE THREAD

**Issue by 12m34** [GardF/FamilienAS#23]

**Comment by 12m34** [comment]
Tror det er lettest å låne utstyr av mamma igjen

**Comment by 12m34** [comment]
Foreslår å gjøre dette også lørdag? @GardF

**Comment by GardF** [comment]
> Foreslår å gjøre dette også lørdag? [@GardF](https://github.com/GardF)

Ok. vi henter vinduspussesakene på lørdag også

**Comment by 12m34** [comment]
Gjenstår å levere vinduspusseutstyr. @GardF

**Comment by 12m34** [comment]
Gard skal vaske raskt over innsiden av glassene som vender mot naboen i de gulehusene. Raskt vaske over med klut og tørke over med pussefille for å fjerne dråpemerker. Trenger ikke å ta de to som typ dekkes av grillen

**Comment by GardF** [comment]
@12m34 Kan vi ikke si at denne utgår. Trykk på close issue dersom du er enig
