### ISSUE TITLE
Planlegge hyttetur i Sommer

### ISSUE THREAD

**Issue by GardF** [GardF/FamilienAS#7]
Gard og Martine skal på ferie sammen i uke 32. Hva skal vi da gjøre

**Comment by GardF** [comment]
Vi ble enige om å dra mandag(5.8) og komme hjem fredag(9.8) slik at vi kan henge med Eystø og Jenny den helga

**Comment by GardF** [comment]
Toppturplan

**Comment by GardF** [comment]
@12m34 Har bilen din hyttelader?

**Comment by 12m34** [comment]
Hyttelader? @GardF

**Comment by GardF** [comment]
Martine har hyttelader og vi kan dermed dra på litt lengre utflukter enn først tenkt

**Comment by 12m34** [comment]
## Mandag: **Ankomst og Merket**


## Tirsdag: **Topptur Rasletind**
[https://www.valdres.no/opplevelser/rasletinden-2105-moh-p4776363](valdres.no)

Avreise(10:00 - 12:00) til Valdresflye Kafé
Bygdinvegen 5795
2953 Beitostølen






## Onsdag **Valdres museum**
15. juni-18. august (høgsesong)
Alle dagar 11 - 17


## Torsdag: **Topptur**

## Fredag: **Utvask og Avreise**

**Comment by 12m34** [comment]
Vi må sjekke at vi begge har turtøy/sko og lignende. @GardF

**Comment by 12m34** [comment]
Skal vi ha med primus og sånn må vi passe på å kjøpe gass.

**Comment by GardF** [comment]
> Vi må sjekke at vi begge har turtøy/sko og lignende. [@GardF](https://github.com/GardF)
- Jeg har fjellstøvler, regnjakke, turbokse, ullundertøy, solbriller, vanter og camelback. 
- Har du fjellstøvler @12m34 ?

Vi mangler faktisk sekk/sekker. Kanskje vi kan låne av Katrine og Stian, eventuelt invistere i en selv da dette egentlig er noe vi mangler. 


> Skal vi ha med primus og sånn må vi passe på å kjøpe gass.
Tror ikke vi trenger primus da dette blir litt mye å drasse med seg for en tur som kun vare rundt 6 timer på det meste.

**Comment by 12m34** [comment]
Pappa anbefaler skogshorn

**Comment by 12m34** [comment]
Skal belegningsteinene være på duken eller på grus

**Comment by 12m34** [comment]
Turen er over og var veldig vellykket <3
